config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books, only: %i[index create new] do
    resources :recaps, only: :index
  end
  resources :recaps, except: :index do
    resources :ratings, only: :create
    resources :favorites, only: :create
  end
  resources :ratings, only: %i[destroy update]
  get 'all_recaps', to: 'recaps#all_recaps', as: :recaps_all
  resources :dashboard, only: :index
  resources :favorites, only: :destroy
  get 'about', to: 'pages#about', as: :about
end

app/models/recap.rb
class Recap < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :ratings, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :summary, presence: true, length: { minimum: 50 }
  # validates :user, uniqueness: { scope: :book }
  validates :title, presence: true, length: { maximum: 20 }
  
  def avg_rating
    ratings.average(:star).to_f
  end
end

app/controllers/recaps_controller.rb
class RecapsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show all_recaps]

  def index
    @recaps = Recap.all
    @book = Book.find(params[:book_id])
  end

  def show
    @recap = Recap.find(params[:id])
    @rating = Rating.new
    @favorite = Favorite.new
    @book_id = Book.find(@recap.book_id)
  end

  def new
    @book_id = params[:book_id]
    @book = Book.find(@book_id)
    @recap = Recap.new(params[:recap])
  end

  def create
    if Book.find(params[:recap][:book_id])
      @book = Book.find(params[:recap][:book_id])
    end
    @recap = Recap.new(recap_params)
    if current_user&.already_recapped?(@book)
      flash.now[:alert] = "You have already recaped this book"
      render :new
    else
      @recap.user = current_user
    end

    if @recap.save
      redirect_to recap_path(@recap), notice: 'Recap was successfully created'
    else
      render :new
    end
  end

  def edit
    @recap = Recap.find(params[:id])
  end

  def update
    @recap = Recap.find(params[:id])
    @recap.update(recap_params)
    redirect_to recap_path(@recap)
  end

  def destroy
    @recap = Recap.find(params[:id])
    @recap.destroy

    redirect_to root_path
  end

  def all_recaps
    if params[:top] == "yes"
      recaps_all = Recap.all
      @recaps = recaps_all.select { |recap| recap.avg_rating > 3 }
    elsif params[:query].present?
      @books = Book.search_by_title_and_author(params[:query])
    else
      @recaps = Recap.all.order('title ASC')
    end
  end

  private

  def recap_params
    params.require(:recap).permit(:summary, :title, :user_id, :book_id, :keypoint)
  end
end

app/views/recaps/_inlineedit.html.erb
<%= simple_form_for @recap, html: { class: "d-none", data: { edit_recap_target: "form", action: "submit->edit-recap#update" } } do |f| %>
        <%= f.input :summary %>
        <%= f.submit "Update" %>
      <% end %>

app/views/recaps/_sumedit.html.erb
<%= simple_form_for @recap, remote: true, html: { class: "d-none", data: { edit_recap_target: "form", action: "submit->edit-recap#update" } } do |f| %>
  <%= f.input :summary, as: :text %>
  <%= f.input :keypoint, label: "Key Points" %>
  <%= f.submit "Update", class: "btn-action" %>
<% end %>

app/views/recaps/all_recaps.html.erb
<%# All recaps search form %>
<%= render "shared/searchform" %>

<div class= "container p-6 mb-4">

  <%# Show highest rated recaps if user clicked the button from home page %>
  <% if params[:top] == "yes" %>
    <h1 class="text-center">Highest Rated Recaps:</h1>
    <br>
    <div class="allrecap-cards">
    <div class="recapcards">
      <%= render "shared/recapcards" %>
    </div>

  <%# Show all recaps that match the search %>
  <% elsif params[:query].present? %>
    <h1 class="text-center">All Recaps for your search:</h1>
    <br>
    <div class="allrecap-cards">
      <div class="recapcards">
        <% @books.each do |book| %>
          <% @recaps = Recap.where(book: book.id) %>
            <%= render "shared/recapcards" %>
        <% end %>
      </div>
    </div>

  <%# Show all recaps %>
  <% else %>
    <h1 class="text-center">All Recaps:</h1>
    <br>
    <div class="allrecap-cards">
      <div class="recapcards">
        <%= render "shared/recapcards" %>
      </div>
    </div>
  <% end %>

</div>

app/views/recaps/edit.html.erb
<%# Edit page for recaps, might remove compleatly in place of inline editing %>
<div class="container pt-2 pb-5 w-50">
  <div class="row justify-content-center">
    <div class="form">
      <h2 style="padding: 12px;">Change this Recap:</h2>

      <%# Edit form for recaps %>
      <%= simple_form_for([@book, @recap])  do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">

          <%# Option to choose different book but only from db list %>
          <p><%= f.label "Choose your book*"%></p>
          <% if @book_id.present?  %>
            <%= f.collection_select :book_id, Book.all, :id, :title, :selected => @book_id, :include_blank => true %>
          <% else %>
            <%= f.collection_select :book_id, Book.all, :id, :title, :include_blank => true %>
          <%end%>

          <%# Other parts open for edit %>
          <%= f.input :title %>
          <%= f.input :summary %>
          <%= f.input :keypoint, label: "Key Points" %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, class: "btn-action" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recaps/index.html.erb
<div class="container my-3">
  <h3>Recaps for: <em><%= @book.title %></em></h3>
  <div style="display: flex;">
    <p style="margin-right: 10px; line-height: 2; font-size: 19px; font-weight: 600;">
      <%= @recaps = Recap.where(book_id: params[:book_id]).count %> Result(s)
    </p>
    <%# Add a new recap to the book. Only show button when user did not recap the book yet %>
    <% unless current_user&.already_recapped?(@book)%>
      <%= link_to new_recap_path(book_id: @book.id) do %>
        <button class="btn-action" type="submit">Add new Recap</button>
      <% end %>
    <% end %>
  </div>

  <%# Cards for all the recaps for the given book %>
  <div class="recapcards my-4">
    <% @recaps = Recap.where(book_id: params[:book_id]) %>
    <%= render "shared/recapcards" %>
  </div>
</div>

app/views/recaps/new.html.erb
<div class="container pt-2 pb-5 w-50">
  <div class="row justify-content-center">
    <div class="form">

      <%# Photo of the book the user is recapping %>
      <div class="card_img text-center">
        <%= image_tag @book.photo_url %>
      </div>

      <%# Titlt with name of book and author %>
      <h2 style="padding: 12px;">Add a new Recap for <%= @book.title %> by <%= @book.author %>.</h2>

      <%# Form to create a new recap %>
      <%= simple_form_for([@recap])  do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.hidden_field :book_id, value: @book_id %>
        <div class="form-inputs">
          <%= f.input :title, lable: "What would you like to call your recap?" %>
          <%= f.input :summary %>
          <%= f.input :keypoint, label: "Key Points" %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, class: "btn-action" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recaps/show.html.erb
<%# All recaps search form %>
<%= render "shared/searchform" %>

<%# Banner with title, author, rating %>
<div class="mb-4">
  <h2 class="text-center"><%= @recap.book.title %></h2>
</div>
<div class="banner" style="background-image: url(<%= image_url "banner.png" %>);">
  <div class="banner-info">
    <h2> Recapped by: <%= @recap.user.username %>
      <% if @recap.user.avatar.attached? %>
        <%= image_tag @recap.user.avatar, class: "avatar" %>
      <% else %>
        <%= image_tag "default-avatar.png", class: "avatar"  %>
      <% end %>
    </h2>
    <h3><%=@recap.title %></h3>
    <% if @recap.avg_rating == 0 %>
      <a href="#rating-cards" class="rating-link"><p class="mt-2">Be the first to leave a review!</p></a>
    <% else %>
      <%= render "shared/rating" %>
    <% end %>
  </div>
</div>

<%# Author of book and Pills tabs %>
<div class="container mt-4">
  <div class="row">
    <div class="container col-lg-7 col-sm-12">
      <h6 style="margin-bottom: 30px;"><strong>Author: <%= @recap.book.author %></strong></h6>

      <%# Names for the tabs %>
      <ul class="nav nav-pills mb-3" style="display: flex; justify-content: center;" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home"
          type="button" role="tab" aria-controls="pills-home" aria-selected="true">Recap Summary</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile"
          type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Book Description</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact"
          type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Key Points</button>
        </li>
      </ul>

      <%# Summary tab %>
      <div class="tab-content mb-5" id="pills-tabContent" style="padding: 10px 30px 0 0;">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <div data-controller="edit-recap">
            <div data-edit-recap-target="infos"><%= simple_format(@recap.summary) %>
              <% if @recap.user == current_user %>
                <i class="fas fa-pen" style="cursor: pointer;" data-action="click->edit-recap#displayForm"></i>
              <% end %>
            </div>
            <%# Inline edit form %>
            <%= render "/recaps/sumedit" %>
          </div>
        </div>

        <%# Book description tab %>
        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
          <%= @description = @recap.book.description %>
        </div>

        <%# Keypoints tab %>
        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
          <%= simple_format(@recap.keypoint) %>
        </div>
      </div>
    </div>

    <%# Right side pannel with book photo and links %>
    <div class="photo-card col-lg-5 col-sm-12 p-3">
      <div style="display: flex; align-items:center;">
        <%= image_tag @recap.book.photo_url %>
        <div class="icon-item">
          <ul class="social-links" style="list-style: none;">

            <%# Add book to library link, only if not in library and not created by curent user %>
            <li class="recap-favorite">
              <% if @recap.user != current_user && !current_user&.already_faved?(@recap) %>
                <%= simple_form_for([@recap, @favorite]) do |f| %>
                  <%= f.button :button  do  %>
                    <i class="social-icon fas fa-bookmark"></i>
                    Add to Library
                  <% end %>
                <% end %>
              <% elsif @recap.user != current_user && current_user&.already_faved?(@recap) %>
                <i class="social-delete-icon fas fa-ban"></i><em> You've already added this to your library.</em>
              <% end %>
            </li>

            <%# Share recap link, take you to whats app with a link to curent page %>
            <li><a href="whatsapp://send?text=I%20found%20this%20recap%20for%20you%20on%20readCaps!%20<%= request.original_url %>" target="_blank">
              <i class="social-icon fas fa-share-alt"></i> Share recap</a>
            </li>

            <%# Add a review link, only if curent user has not reviewed and recap was not created by curent user %>
            <li>
              <% if current_user != @recap.user && !current_user&.already_rated?(@recap) %>
                <i class="social-icon fas fa-plus" data-bs-toggle="modal" data-bs-target="#exampleModal"></i> Add Review
              <%end%>
            </li>

            <%# Edit recap link, only if recap was created by curent user.
            Need to update this to the inline edit that we have at the bottom of the summary %>
            <li>
              <% if @recap.user == current_user %>
                <%= link_to edit_recap_path(@recap) do %>
                  <i class="social-icon fas fa-pencil-alt"></i> Edit my recap
                <% end %>
              <% end %>
            </li>

            <%# Delete recap link, only if recap was created by curent user %>
            <li>
              <% if @recap.user == current_user %>
                <%= link_to recap_path(@recap), method: :delete, data: { confirm: "Are you sure you want to delete this recap?"} do %>
                  <i class="social-icon fas fa-trash" ></i> Delete recap
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <%# Other recaps of the selected book. Should display either all recaps except for the recap we are on OR No further recaps available. %>
      <div class="mt-5 col-lg-12 col-sm-12">
        <% @recaps_like_this = Recap.where(book_id: @recap.book).filter { |recap| recap.id != @recap.id} %>
        <% if @recaps_like_this.present? %>
          <h3>Other recaps for this book</h3>
        <% elsif !current_user&.already_recapped?(@book_id) %>
          <h3>This is the only recap for this book</h3>
          <%= link_to new_recap_path(book_id: @book_id) do %>
            <button class="btn-action" type="submit">Write your own</button>
          <% end %>
        <% else %>
          <h3>This is the only recap for this book</h3>
        <% end %>
        <% @recaps_like_this.each do |recap| %>
          <%= link_to recap, style:"text-decoration: none; color: black" do %>
            <div class="card-all my-3" style="flex-direction: row-reverse; justify-content: center; box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
              <p><strong>Preview: </strong><%= recap.summary.split.first(40).join(" ") %>...</p>
              <div class= "card-all-infos" style="width: 100%;">
                <h2 style="width: 150px;"><%= recap.title %></h2>
                <div style="display: flex; margin-top: 5px;">
                  <p style="margin-right: 5px;"><%= recap.user.username %></p>
                  <% if recap.user.avatar.attached? %>
                    <%= image_tag recap.user.avatar, class: "recap-avatar" %>
                  <% else %>
                    <%= image_tag "default-avatar.png", class: "recap-avatar"  %>
                  <% end %>
                </div>
                <% if recap.avg_rating == 0 %>
                  <p>0 Ratings</p>
                <% else %>
                  <i class="fas fa-star m-2" style="color: #F6AE2D;"></i><%= recap.avg_rating %>
                <% end %>
              </div>
            </div>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>


  <%# Review cards %>
  <div class="review-container" id="rating-cards">
    <div class="row">
      <div class="col-12 col-md-6 col-lg-6">

        <%# Header for revies section %>
        <div class="review-header">
          <h3>Reviews on <%= @recap.user.username %>'s recap</h3>
          <% if !user_signed_in? %>
            <p><em style="color: #EB9C0A; font-size: 13px;">Please login to leave a review.</em></p>
          <% elsif current_user != @recap.user && !current_user&.already_rated?(@recap) %>
            <button type="button" class="btn-action" data-bs-toggle="modal" data-bs-target="#exampleModal">Add review</button>
          <%elsif current_user == @recap.user %>
            <p><em style="color: #EB9C0A; font-size: 13px;"> </em></p>
          <%else%>
            <p><em style="color: #EB9C0A; font-size: 13px;">You have already rated this recap.</em></p>
          <%end%>
        </div>

        <%# All reviews %>
        <div id="anchor-review">
          <% @recap.ratings.each do |recap| %>
            <div class="review-card">
              <p id="rating-<%= recap.id %>"></p>
              <div style="display: flex;">
                <div style="margin-right: 10px;">
                  <% if recap.user.avatar.attached? %>
                    <%= image_tag recap.user.avatar, class: "avatar" %>
                  <% else %>
                    <%= image_tag "default-avatar.png", class: "avatar" %>
                  <% end %>
                </div>
                <div>
                  <h4><%= recap.user.username %></h4>
                  <p> <i class="fas fa-star" style="color: #F6AE2D;"></i> <%= recap.star.to_f %></p>
                </div>
              </div>
              <p><%= recap.comment %></p>
              <% if recap.user == current_user %>
                <%= link_to rating_path(recap), method: :delete, remote: true, data: { confirm: "Are you sure you want to delete this review?"} do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%# Modal with review form %>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Tell us what you think</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for([ @recap, @rating ], remote: true) do |f| %>
            <%= f.input :comment, label: "Comment"  %>
            <%= f.input :star, label: "Rating", collection: 0..5, include_blank: false, include_hidden: false %>
            <%= f.submit "Submit review", class: "btn-action" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>