config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books, only: %i[index create new] do
    resources :recaps, only: :index
  end
  resources :recaps, except: :index do
    resources :ratings, only: :create
    resources :favorites, only: :create
  end
  resources :ratings, only: %i[destroy update]
  get 'all_recaps', to: 'recaps#all_recaps', as: :recaps_all
  resources :dashboard, only: :index
  resources :favorites, only: :destroy
  get 'about', to: 'pages#about', as: :about
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-warning fade show m-1" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning fade show m-1" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# Footer %>
<div class="footer">

  <%# Social media links. We will need actual social media accounts to keep these. %>
  <div class="footer-links">
    <a href="https://www.instagram.com/accounts/login/" target=”_blank”><i class="fab fa-instagram"></i></a>
    <a href="https://de-de.facebook.com/" target=”_blank”><i class="fab fa-facebook"></i></a>
    <a href="https://de.linkedin.com/" target=”_blank”><i class="fab fa-linkedin"></i></a>
  </div>

  <%# Our photos that link you to the about page %>
  <%= link_to about_path, style:"text-decoration: none;" do %>
    <div class="footer-copyright">
      Team <i class="fas fa-heart"> </i>
      <%= image_tag "nicola.png", class: "avatar-xs" %>
      <%= image_tag "anna.png", class: "avatar-xs" %>
      <%= image_tag "shell.png", class: "avatar-xs" %>
      <%= image_tag "mel.png", class: "avatar-xs"  %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<%# Navbar %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <%# readCaps logo linked to the home page %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <h2 class="logo">read<em>Caps</em></h2>
    <% end %>

    <%# This is the dropdown menu on the navbar when the screen is smaller than 576px %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <%# User avatar dropdown menu if user is signed in%>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%# Do we want this heart that takes you to the dashboard??
            #<li class="nav-item active">
              <a class="nav-link" href="<%= dashboard_index_path "><i class="dashboard-icon far fa-heart" style="color: #F6AE2D;"></i></a>
            </li> %>

            <%# Avatar button if user has an avatar if not standard avatar %>
            <div role='button' id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, class: "avatar dropdown-toggle" %>
              <% else %>
                <%= image_tag "default-avatar.png", class: "avatar dropdown-toggle" %>
              <% end %>
            </div>

            <%# Dropdown menu %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%# Link to the curent users dashboard %>
              <%= link_to "Dashboard", dashboard_index_path, class: "dropdown-item" %>

              <%# Link to add a new recap %>
              <%= link_to "Add new recap", new_book_path, class: "dropdown-item" %>

              <%# Link to logout  %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>

          <%# Log in button if not logged in %>
          <li class="nav-item">
            <%= link_to new_user_session_path do %>
              <button class="btn-action" type="submit">Log in</button>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_rating.html.erb
<%# Partial for recap rating %>
<div class="mt-3">
  <% @recap.avg_rating.round.times do %>
    <i class="fas fa-star" style="color: #F6AE2D;"></i>
  <% end %>
  <strong><%= @recap.avg_rating %></strong>
</div>
<a href="#rating-cards" class="rating-link"><p><%= @recap.ratings.count %> Ratings</p></a>

app/views/shared/_recapcards.html.erb
<%# Cards for the Recaps %>
<% @recaps.each do |recap| %>
  <%= link_to recap, style:"text-decoration: none; color: black", class: "recapcard" do %>

    <%# Image url for background%>
    <img src="<%= recap.book.photo_url %>" class="card__image">

    <%# Info in the tab and pop-up %>
    <div class="card__overlay">
      <div class= "card__header">
        <svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path /></svg>

        <%# Avatar %>
        <% if recap.user.avatar.attached? %>
          <%= image_tag recap.user.avatar, class: "card__thumb" %>
        <% else %>
          <%= image_tag "default-avatar.png", class: "card__thumb"  %>
        <% end %>

        <%# Title, Username, Rating %>
        <div class="card__header-text">
          <h2 class="card__title"><%= recap.title %></h2>
          <span class="card__status"><%= recap.user.username %>
            <% if recap.avg_rating == 0 %>
              <i class="fas fa-star" style="color: #F6AE2D; margin-right: 8px;"></i>0.0
            <% else %>
              <i class="fas fa-star" style="color: #F6AE2D; margin-right: 8px;"></i><%= recap.avg_rating %>
            <% end %>
          </span>
        </div>
      </div>

      <%# Description %>
      <p class="card__description"><%= recap.summary.split.first(30).join(" ") %>...</p>
    </div>
  <%end%>
<%end%>

app/views/shared/_searchform.html.erb
<%# Search for for all of the recaps in the database %>
<div class="book_search_form">
  <div class="booksearch__container">
    <%= simple_form_for :search, url: recaps_all_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "booksearch__input",
        placeholder: "Search by title, author"
      %>
    <% end %>
  </div>
</div>