config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books, only: %i[index create new] do
    resources :recaps, only: :index
  end
  resources :recaps, except: :index do
    resources :ratings, only: :create
    resources :favorites, only: :create
  end
  resources :ratings, only: %i[destroy update]
  get 'all_recaps', to: 'recaps#all_recaps', as: :recaps_all
  resources :dashboard, only: :index
  resources :favorites, only: :destroy
  get 'about', to: 'pages#about', as: :about
end

app/views/pages/about.html.erb
<div class= "container p-6 mb-4">
  <h2 class="text-center my-3">This site was made with lots of fun by these <strong>amazing</strong> women!</h2>
  <%# Should add a little mor to the about page. %>
  <%# Photos of the 4 of us %>
  <div class="about-photos mt-4">
    <div class="text-center main-photo"><%= image_tag "nick.jpg", class: "main-photo" %><h4 class="text-center">Nicola</h4></div>
    <div class="text-center main-photo"><%= image_tag "melissa.jpg", class: "main-photo" %><h4 class="text-center">Melissa</h4></div>
    <div class="text-center main-photo"><%= image_tag "michelle.jpg", class: "main-photo" %><h4 class="text-center">Michelle</h4></div>
    <div class="text-center main-photo"><%= image_tag "anna.jpg", class: "main-photo" %><h4 class="text-center">Anna</h4></div>
  </div>
  <br>
  <br>

  <%# Group photo %>
  <div class="row justify-content-md-center">
    <%= image_tag "group.jpg", class: "group-photo" %>
  </div>
  <br>
  <br>
</div>

app/views/pages/home.html.erb
<%# All recaps search form %>
<%= render "shared/searchform" %>

<%# Links above banner %>
<div class="home-links mb-3">
  <ul class="nav justify-content-center">

    <%# Link to all recaps %>
    <li class="nav-item">
      <%= link_to "All Recaps", recaps_all_path, class: "nav-link" %>
    </li>

    <%# Link to top rated recaps %>
    <li class="nav-item">
      <%= link_to "Top Recaps", recaps_all_path(top: 'yes'), class: "nav-link" %>
    </li>

    <%# Link to user dashboard if logged in %>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "My Dashboard", dashboard_index_path, class: "nav-link" %>
      </li>
    <% end %>

    <%# Link to new recap page %>
    <li class="nav-item">
      <%= link_to "New Recap", new_book_path, class: "nav-link" %>
    </li>
  </ul>
</div>

<%# Banner %>
<div class="banner" style="background-image: url(<%= image_url "banner.png" %>);">
  <div class="container-home">
    <h2>Welcome to</h2>
    <h1>read<em>Caps</em></h1>
    <p>Find recaps of your favorite books</p>
    <%= link_to books_path do %> <button class="button-action" type="submit">All Books</button>
    <% end %>
  </div>
</div>

<%# Newest recaps carousel %>
<div class= "container p-6 my-4">
  <h1 class="text-center mb-3">Latest recaps</h1>
   <div class="recapcards">
      <% @recaps = Recap.order("created_at DESC").limit(6) %>
      <%= render "shared/recapcards" %>
    </div>
</div>

<%#Gold Silver Bronze medals for top rated recappers, should make these clickable to get redirected to a user summary like page %>
<h1 class="text-center mb-2">Ready, Set, Gold!</h1>
<h5 class="text-center mb-2">Our best rated read<em>Cappers</em></h5>

<%#Best rated User through recaps  %>
<div class="ranking-cards">
  <div class = "best-ranked justify-content-center">

    <%# User ranked in 1st place %>
    <div class="first">
      <i class="fas fa-solid fa-award" style="color: #F6AE2D; font-size: 50px;"></i>
      <%= @top_users[0].username %>
      <% if @top_users[0].avatar.attached? %>
        <%= image_tag @top_users[0].avatar, class: "recap-avatar" %>
      <% else %>
        <%= image_tag "default-avatar.png", class: "recap-avatar"  %>
      <% end %>
      <i class="fas fa-star" style="color: #F6AE2D; font-size: 20px; padding: 5px;"></i>
      <p style="font-size: 20px; font-weight: bold; display: flex; flex-direction: column;"><%= @top_users[0].avg_received_ratings%></p>
    </div>

    <%# User ranked in 2nd place %>
    <div class="second">
      <i class="fas fa-solid fa-award" style="color: silver; font-size: 50px;"></i>
      <%= @top_users[1].username %>
      <% if @top_users[1].avatar.attached? %>
        <%= image_tag @top_users[1].avatar, class: "recap-avatar" %>
      <% else %>
        <%= image_tag "default-avatar.png", class: "recap-avatar"  %>
      <% end %>
      <i class="fas fa-star" style="color: #F6AE2D; font-size: 20px; padding: 5px;"></i>
      <p style="font-size: 20px; font-weight: bold; display: flex; flex-direction: column;"><%= @top_users[1].avg_received_ratings%></p>
    </div>

    <%# User ranked in 3rd place %>
    <div class="third">
      <i class="fas fa-solid fa-award" style="color: #d6b4a4; font-size: 50px;"></i>
      <%= @top_users[2].username %>
      <% if @top_users[2].avatar.attached? %>
        <%= image_tag @top_users[2].avatar, class: "recap-avatar" %>
      <% else %>
        <%= image_tag "default-avatar.png", class: "recap-avatar"  %>
      <% end %>
      <i class="fas fa-star" style="color: #F6AE2D; font-size: 20px; padding: 5px;"></i>
      <p style="font-size: 20px; font-weight: bold; display: flex; flex-direction: column;"><%= @top_users[2].avg_received_ratings%></p>
    </div>
  </div>
</div>

<br>
<br>

<%# Top author cards. Need to decide if we are keeping this and if we are we need to give it functionality %>
<div class= "container p-6 my-4">
  <h1 class="text-center mb-6">Top Authors</h1>
  <% sorted_authors = @top_authors.sort_by { |author, count| -count } %>
  <div class = "container">
    <div class="cards-author">
      <%= link_to books_path(query: sorted_authors[0][0]), style: "text-decoration: none;" do %>
        <div class="author" style="background-image: url('<%= image_path("rowling.jpg") %>')">
          <h4><%= sorted_authors[0][0] %></h4>
        </div>
      <% end %>
        <%= link_to books_path(query: sorted_authors[1][0]), style: "text-decoration: none;" do %>
        <div class="author" style="background-image: url('<%= image_path("stieg_larsson.jpg") %>')">
          <h4><%= sorted_authors[1][0] %></h4>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>