config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books, only: %i[index create new] do
    resources :recaps, only: :index
  end
  resources :recaps, except: :index do
    resources :ratings, only: :create
    resources :favorites, only: :create
  end
  resources :ratings, only: %i[destroy update]
  get 'all_recaps', to: 'recaps#all_recaps', as: :recaps_all
  resources :dashboard, only: :index
  resources :favorites, only: :destroy
  get 'about', to: 'pages#about', as: :about
end

app/models/book.rb
class Book < ApplicationRecord
  before_create :set_default_description
  has_many :recaps, dependent: :destroy

  validates :title, presence: true
  # validates :author, presence: true

  include PgSearch::Model

  multisearchable against: %i[title author]

  pg_search_scope :search_by_title_and_author,
                  against: %i[title author],
                  using: {
                    tsearch: { prefix: true }
                  }

  private

  def set_default_description
    self.description = "No description given" if description.nil?
  end
end

app/controllers/books_controller.rb
require "open-uri"
require "json"

class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @books = Book.all
  end

  def new
    @random_books = Book.order('RANDOM()').limit(8)
    @search = params[:query]
    if @search.present?
      @db_books = Book.search_by_title_and_author(params[:query])
      url = "https://www.googleapis.com/books/v1/volumes?q=#{@search}&projection=lite&maxResults=8&orderBy=relevance&langRestrict=en&key=#{ENV['GOOGLE_API_KEY']}"
      user_serialized = URI.open(url).read
      user = JSON.parse(user_serialized)
      @api_books = user["items"]
    end
    @book = Book.new(params[:book])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to new_recap_path(book_id: @book.id)
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :description, :photo_url)
  end
end

app/views/books/index.html.erb
<%# All recaps search form %>
<%= render "shared/searchform" %>

<div class="container mb-5">
  <h1 class="text-center title-card">All available books with recaps</h1>
  <br>

  <%# Book cards %>
  <div class="cards">
    <% books_sorted = @books.order('title ASC')%>
    <% books_sorted.each do |book| %>
      <%= link_to book_recaps_path(book), class: "a", style: "color: $black;" do %>

        <%# Interactive cover when hovered %>
        <div class="card-book">
          <div class="book-card__cover">
            <div class="book-card__book">
              <div class="book-card__book-front">
                <%= image_tag book.photo_url, class: "book-card__img" %>
              </div>
              <div class="book-card__book-back"></div>
              <div class="book-card__book-side"></div>
            </div>
          </div>

          <%# Title and Author %>
          <div class="card-info">
            <h2><%= book.title %></h2>
            <p><%= book.author %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container mb-5">

  <% if !params[:query].present? %>

  <%# Books from the db for them to choose from %>
  <%# This will need to be changed to requested books once we have that functionality %>
    <h1 class="text-center title-card">Recap a book that another user has recaped already</h1>
    <h2 class="text-center title-card">or search for a different book</h2>

    <%# Search form to find a book to recap %>
    <div class="book__body">
      <div class="booksearch__container">
        <%= simple_form_for :search, url: new_book_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "booksearch__input",
            placeholder: "What book whould you like to recap?"
          %>
        <% end %>
      </div>
    </div>

    <br>

    <div class="cards">
      <% @random_books.each do |book| %>
        <%= link_to new_recap_path(book_id: book.id) do %>
          <div class="card-book">
            <div class="book-card__cover">
              <div class="book-card__book">
                <div class="book-card__book-front">
                  <%= image_tag book.photo_url, class: "book-card__img" %>
                </div>
                <div class="book-card__book-back"></div>
                <div class="book-card__book-side"></div>
              </div>
            </div>
            <div class="card-info">
              <h2><%= book.title %></h2>
              <p><%= book.author %></p>
            </div>
          </div>
        <%end%>
      <%end%>
    </div>
  <% end %>

  <% if params[:query].present? %>

    <%# Books from the db that match search %>
    <h1 class="text-center title-card">Books with recaps</h1>

    <%# Search form to find a book to recap %>
    <div class="book__body">
      <div class="booksearch__container">
        <%= simple_form_for :search, url: new_book_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "booksearch__input",
            placeholder: "What book whould you like to recap?"
          %>
        <% end %>
      </div>
    </div>

    <br>

    <div class="cards">
      <% @db_books.each do |book| %>
        <%= link_to new_recap_path(book_id: book.id) do %>
          <div class="card-book">
            <div class="book-card__cover">
              <div class="book-card__book">
                <div class="book-card__book-front">
                  <%= image_tag book.photo_url, class: "book-card__img" %>
                </div>
                <div class="book-card__book-back"></div>
                <div class="book-card__book-side"></div>
              </div>
            </div>
            <div class="card-info">
              <h2><%= book.title %></h2>
              <p><%= book.author %></p>
            </div>
          </div>
        <%end%>
      <%end%>
    </div>

    <br>
    <br>

    <%# First 8 books from the google books api that meet the search %>
    <h1 class="text-center title-card">More books ...</h1>

    <br>

    <div class="cards">
      <% @api_books.each do |book| %>

        <%# Assigning all the necessary parameters from the api %>
        <% photo_url = "https://books.google.com/books/content?id=#{book['id']}&printsec=frontcover&img=1&zoom=1&source=gbs_api" %>
        <% title = book["volumeInfo"]["title"] %>
        <% authors = book["volumeInfo"]["authors"] %>
        <% if !authors.nil? %>
          <% author = authors[0] %>
        <% else %>
          <% author = "No Author" %>
        <%end%>
        <% description = book["volumeInfo"]["description"] %>

        <%# Hidden form to add the chosen book to the database %>
        <%= simple_form_for @book do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <%= f.hidden_field :title, value: title %>
          <%= f.hidden_field :author, value: author %>
          <%= f.hidden_field :description, value: description %>
          <%= f.hidden_field :photo_url, value: photo_url %>
        <div class="card-book">
          <%= f.button :submit, "Create Recap" %>
        <% end %>

          <div class="book-card__cover">
            <div class="book-card__book">
              <div class="book-card__book-front">
                <%= image_tag photo_url, class: "book-card__img" %>
              </div>
              <div class="book-card__book-back"></div>
              <div class="book-card__book-side"></div>
            </div>
          </div>
          <div class="card-info">
            <h2><%= title %></h2>
            <p><%= author %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>